language: R
cache: packages
sudo: required
bioc_packages:
- graph
- RBGL
- Rgraphviz
os:
- linux
- osx
before_install:
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then tlmgr install boxedminipage; fi
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then sudo tlmgr install a4wide boxedminipage;
  fi
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then curl -O http://r.research.att.com/libs/gfortran-4.8.2-darwin13.tar.bz2;
  sudo tar fvxz gfortran-4.8.2-darwin13.tar.bz2 -C /; fi
after_success:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then R CMD INSTALL --build $PKG_TARBALL; fi
deploy:
  provider: releases
  api_key:
    secure: 2TJ0jYFEKBxxSkdUfyaG/tNFOjvhQPI1SWkJVf8KffP6OvKdfyg5afDvtUedltoRHCitu/ogI91Ot7ZPmVoBiMA6Y/6aYLKNRNrFAVmRYZCNvU6VAkF0/E13slhyW1hGO/Er8xxoV4S55o9I3teAvxOvQWo1jur+NKaQ96mtlT/QBE/JNEpKn2uMpdhFwMgTZ7ccTsdys/X3DRd+yQdyhZVmT7jn1gpAbYOeGbkfb4vwkPPA0kIRSL8RUHx8r3k9qFYOW1ILMG8xZ1oNral7jRofHVNj6rSx/GOB9vTVGk27YHwy3drk+/Vgi5G2JtZi4YJib0Tq21CtZBBcXQR6Q7sCD8p6F51zq10y5MPIrzMovNM3BDILoiwg8hPrPtIZ6wfgCj71mmqQs489HR2FIszJvlJ/9ns2ZDnAxcQFMBTpzxV6Ft4dU+OmTwIsu6uhqhnzZbA9ZJK7djureoYLR/Qn0ZaO9ROteJ0LcZtIlMGct/sHfFqWe/B4iir5mqXys+JSCnfdIeKuA5aLAlWxgzlpjERtWuL9Z2DwIXoEo/160qh3CgX29KCqIW/5T64+jq4ulleMmenp9w/iqIMv9+fp93bkuiKbdI/KHM/HTA73S9L1O5Z8E8krfJJz+d25KjH9llM91Is/txUHFSkMDgjdq7I0HQXuh6mIKJTKqXc=
  skip_cleanup: true
  file_glob: true
  file: gRain_*.t*gz
  on:
    repo: hojsgaard/gRain
    tags: true
    condition: "$TRAVIS_OS_NAME == osx" 