language: R
cache: packages
sudo: required
dist: trusty
bioc_packages:
- graph
- RBGL
- Rgraphviz
os:
- linux
- osx
r_github_packages: hojsgaard/gRbase
before_install:
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then tlmgr install boxedminipage; fi
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then sudo tlmgr install a4wide boxedminipage; fi
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then curl -O http://r.research.att.com/libs/gfortran-4.8.2-darwin13.tar.bz2; sudo tar fvxz gfortran-4.8.2-darwin13.tar.bz2 -C /; fi
install:
- R -e 'source("http://bioconductor.org/biocLite.R"); biocLite(c("graph","RBGL","Rgraphviz"))'
after_success:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then rm $PKG_TARBALL; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then rm gfortran-4.8.2-darwin13.tar.bz2; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then R CMD build .; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then R CMD INSTALL --build $PKG_TARBALL; fi
deploy:
  provider: releases
  api_key:
    secure: uvjknEkoOqegV0KLYemx3J/1jaPbk0iIzvhjO/a0yHDK9D1Ut0ieNoezCC8A43Uwf2isSMudxXHn3L2Ot2DxQZbyDpsu61cs6rWAcGrjdq79R9ZzuCOznuIkN4jd+gv68B30ir6Vmb1F5mFLZoXp3PEwosUWiDXlHqgnzqb3+vrxvqpCouOg+VCUwe7DDJyPd1eg97stUD47V6GOx+x2WjS2OGHWYS/ire2OzUUivxeM4zguS6FW6c3MMPveVGUAUMXhw76xdr9AKfDL6wzUCRw3B6dItSIPb2wsAycF/VPOx8jHYe21DmU/ikMM5Bw0IgIseEGkdvbSw+4cniacMi6CaZn2HnqxHvAnEidp7q3KkN70TQ+vKJXsMqqUPxeBCQ+TTy0kgqwVJzB8ajHWSvmT/vB7bPGDbtp8yCi7Hi1uwwG5n2wVnx0uiFpRtlBsLY1w1Rqwc5UgOPPIyNn998QBmphXil8u3fa29OKeWorPODi228s3w0kPY7IdMKrX7wGveiJsoJNbnWRscyg1uEpKrNg80gsakRqlvybMb26Sg0mTG86k8T5m+nK/g6uOsyzDYjGeWJqdsD+/jRlZrCfXuQneR+G0gQMh1+CjZ07mphNUtD084IwFcNazhGVAneG5AvjGgbq7ePM9EarjUXypTxVffJHmnybcgANLwv0=
  skip_cleanup: true
  file_glob: true
  file: gRain_*.t*gz
  on:
    repo: hojsgaard/gRain
    tags: true
    condition: "$TRAVIS_OS_NAME == osx"
