language: R
cache: packages
sudo: required
bioc_packages:
- graph
- RBGL
- Rgraphviz
os:
- linux
- osx
before_install:
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then tlmgr install boxedminipage; fi
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then sudo tlmgr install a4wide boxedminipage;
  fi
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then curl -O http://r.research.att.com/libs/gfortran-4.8.2-darwin13.tar.bz2;
  sudo tar fvxz gfortran-4.8.2-darwin13.tar.bz2 -C /; fi
deploy:
  provider: releases
  api_key:
    secure: Y8J/3linU4tHe1kVTfQzr3hyVmrGoDHr5uoLs9C3sYhKLlW0FugWDe+2AbomiPT/0NxviBZSc8d5B8ioV7Xiy/ZpNJSg4ZwDetAYCYFP4brHP9KVN1Kg0JVV4wp1qT/+vN9ihHSLPX2OGkAVFPbb9ZQ8pBhvKj0p1/GpH6RbN9E03vpgVSeZX9oK1EL1PWGhAZe1KtuAR9ER39bU+qqTQIMqRLWk2tMYT1UA67nh82BjgBU8vnXFzoGWSwWZqhPkFcwfns+k93Ya1YNEvRjT7ZSHbHkTZvrNJY8i4xh2dVfbrxDot+bJfLtqefUbsnHypLi2oX0yoarjmkbnmGIF0TIbEtg9eX/XHG4IwJvo3VI/iwCCz0qLls+0fQ0Cb5vvQwrCLYTau6zWe9ljTIQDtMwUziGXEOXgrzoPs/3BK1XX3B8oMuLJecd0INrTVcjHD/EbMDsNyrqGcN/QaXmbQMrJEiqJpDmK/VEQAPcsNVmBnwtmBQd31MXDMWabdMHBn4gDfAgm+TUH4Ll0h7/oPJMUQVTPdko7Z0ncaSQdhy72liBosHW3PTtxo02vqqH2Ng+ji9LDBnqKn2U42HWNj9J6eR8kBfZxr9cEYLatV52NU7qgkSz0RQQ9N+NU8bgkzc7IdaXlT5FoWuP94AFJ6evfCwQcU5RBrgD+Mfc8Ge8=
  skip_cleanup: true
  file_glob: true
  file: gRain_*.t*gz
  on:
    repo: hojsgaard/gRain
    tags: true
